### PR TITLE
Update GHA to get notifications

### PR DESCRIPTION
**Pull request by haydentherapper**
I'm hoping this will change update who gets notified on action failure. https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs says that only updating the cron syntax or enabling the workflow will change it, but given the last update to just change yaml->yml, I'm hoping this fixes notifications. 

Signed-off-by: Hayden B <hblauzvern@google.com>

### CODE REVIEW

**Review by asraa — COMMENTED** [review]
what is the change here besides the commenting update?

**Comment by haydentherapper** [comment]
I'm seeing if this changes who the "owner" of the GHA is. Right now, Bob is getting emails whenever they fail. I'd prefer I get the emails. This isn't a great setup regardless, but there isn't a way to configure a group of emails for GHA failures. I need to file a FR

**Review by asraa — APPROVED** [review]
OH got it. 

> Right now, Bob is getting emails whenever they fail. 

Yeah, I think it's the workflow author by default. That being said, I assume you get the file_issue emails?

**Comment by haydentherapper** [comment]
I do see the file issue emails, yea!

**Pull request merged**
